FROM stefanscherer/node-windows:8-windowsservercore


ENV SAPNWRFC_HOME C:\nwrfcsdk

WORKDIR $SAPNWRFC_HOME


COPY ../nwrfsdk .

ENV DEPENDENCY_PATH=.\lib
ENV PATH=%DEPENDENCY_PATH%;%PATH%

WORKDIR /code


COPY package.json /code/package.json
RUN npm install --production
COPY . .
CMD ["node", "app.js"]
