
FROM node:14-alpine
RUN apt-get update && \
    apt-get install -y python3 && \
    apt-get install -y build-essential

RUN apt-get install -y libx11-xcb1 libxcb-dri3-0 libxtst6 libnss3 libcups2 libxss1 libasound2 libatk-bridge2.0-0 libgtk-3-0

WORKDIR /app


COPY package*.json ./

RUN npm install --build-from-source --production

COPY . .

CMD ["node", "app.js"]
