FROM stefanscherer/node-windows:8-windowsservercore


ENV SAPNWRFC_HOME C:\nwrfcsdk

WORKDIR .

COPY nwrfcsdk/ .

ENV DEPENDENCY_PATH=.\lib
ENV PATH=%DEPENDENCY_PATH%;%PATH%

WORKDIR /code


COPY . .
RUN npm install node-rfc@3.0.0
CMD ["node", "app.js"]
